name: Run Function

on:
  schedule:
    - cron: "*/1 * * * *"  # Esto se ejecuta cada minuto

jobs:
  run_function:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # O la versión de Node.js que estés usando

    - name: Ejecutar script
      run: node path/to/your-function.js